//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReporterWPF
{
    using System;
    using System.Collections.Generic;
    
    public partial class DataSend
    {
        public int ID { get; set; }
        public Nullable<int> ID_Station { get; set; }
        public Nullable<System.DateTime> DateTime { get; set; }
        public Nullable<byte> BO0 { get; set; }
        public Nullable<byte> BO1 { get; set; }
        public Nullable<byte> BO2 { get; set; }
        public Nullable<byte> BO3 { get; set; }
    }
}
