//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReporterWPF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Node_Mapping
    {
        public int ID { get; set; }
        public Nullable<int> ID_Station { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> DateTimeCreate { get; set; }
        public Nullable<System.DateTime> DateTimeEdit { get; set; }
        public Nullable<bool> IsPumpStation { get; set; }
        public byte DB0 { get; set; }
        public byte DB1 { get; set; }
        public byte DB2 { get; set; }
        public byte DB3 { get; set; }
        public byte DB4 { get; set; }
        public byte DB5 { get; set; }
        public byte DB6 { get; set; }
        public byte DB7 { get; set; }
        public byte DB8 { get; set; }
        public byte DB9 { get; set; }
        public short AI0 { get; set; }
        public short AI1 { get; set; }
        public short AI2 { get; set; }
        public short AI3 { get; set; }
        public short AI4 { get; set; }
        public short AI5 { get; set; }
        public short AI6 { get; set; }
        public short AI7 { get; set; }
        public short AI8 { get; set; }
        public short AI9 { get; set; }
        public short AI10 { get; set; }
        public short AI11 { get; set; }
        public short AI12 { get; set; }
        public short AI13 { get; set; }
        public short AI14 { get; set; }
        public short AI15 { get; set; }
        public short AI16 { get; set; }
        public short AI17 { get; set; }
        public short AI18 { get; set; }
        public short AI19 { get; set; }
        public short AI20 { get; set; }
        public short AI21 { get; set; }
        public short AI22 { get; set; }
        public short AI23 { get; set; }
        public short AI24 { get; set; }
        public short AI25 { get; set; }
        public short AI26 { get; set; }
        public short AI27 { get; set; }
        public short AI28 { get; set; }
        public short AI29 { get; set; }
        public float Low_A0 { get; set; }
        public float High_A0 { get; set; }
        public float Low_A1 { get; set; }
        public float High_A1 { get; set; }
        public float Low_A2 { get; set; }
        public float High_A2 { get; set; }
        public float Low_A3 { get; set; }
        public float High_A3 { get; set; }
        public float Low_A4 { get; set; }
        public float High_A4 { get; set; }
        public float Low_A5 { get; set; }
        public float High_A5 { get; set; }
        public float Low_A6 { get; set; }
        public float High_A6 { get; set; }
        public float Low_A7 { get; set; }
        public float High_A7 { get; set; }
        public float Low_A8 { get; set; }
        public float High_A8 { get; set; }
        public float Low_A9 { get; set; }
        public float High_A9 { get; set; }
        public float Low_A10 { get; set; }
        public float High_A10 { get; set; }
        public float Low_A11 { get; set; }
        public float High_A11 { get; set; }
        public float Low_A12 { get; set; }
        public float High_A12 { get; set; }
        public float Low_A13 { get; set; }
        public float High_A13 { get; set; }
        public float Low_A14 { get; set; }
        public float High_A14 { get; set; }
        public float Low_A15 { get; set; }
        public float High_A15 { get; set; }
        public float Low_A16 { get; set; }
        public float High_A16 { get; set; }
        public float Low_A17 { get; set; }
        public float High_A17 { get; set; }
        public float Low_A18 { get; set; }
        public float High_A18 { get; set; }
        public float Low_A19 { get; set; }
        public float High_A19 { get; set; }
        public float Low_A20 { get; set; }
        public float High_A20 { get; set; }
        public float Low_A21 { get; set; }
        public float High_A21 { get; set; }
        public float Low_A22 { get; set; }
        public float High_A22 { get; set; }
        public float Low_A23 { get; set; }
        public float High_A23 { get; set; }
        public float Low_A24 { get; set; }
        public float High_A24 { get; set; }
        public float Low_A25 { get; set; }
        public float High_A25 { get; set; }
        public float Low_A26 { get; set; }
        public float High_A26 { get; set; }
        public float Low_A27 { get; set; }
        public float High_A27 { get; set; }
        public float Low_A28 { get; set; }
        public float High_A28 { get; set; }
        public float Low_A29 { get; set; }
        public float High_A29 { get; set; }
    }
}
